### ISSUE TITLE
[4.6.1] Représenter les unités Paul

### ISSUE THREAD

**Issue by Jordan-B1** [Prophecy-eip/Maths#14]
as:
Non pertinent

i want:
Avoir une représentation idéale des unités de 9eme age

description:
La bibliothèque de mathématique pour fonctionner à besoin d'une représentation en Rust lui permettant de stocker toutes les informations dont elle a besoin pour faire les prophéties

definition of done:

    * Le répertoire doit contenir une structure en Rust reprenant
       * Les stats d'une unités
       * L'état d'une unité (fuite, panique...)
       * La position d'une unité
    * Des unit tests sur la structure créée

workload: 3

**Comment by Pepiloto** [comment]
Done in #32
